### ISSUE TITLE
Question - Is it possible to pull the processed NVD CVE files?

### ISSUE THREAD

**Issue by Cosmin-Apopei** [dependency-check/azuredevops#122]
Hello, I was looking into ways of speeding up the amount of time the dependency check scan took when ran in a Azure Pipeline using the "OWASP Dependency Check" task.

Reading the logs, it seems that a lot of the time is going into downloading and processing the CVE files:

<pre>
<code>
[INFO] Processing Complete for NVD CVE - 2016  (18858 ms)
[INFO] Processing Started for NVD CVE - 2018
[INFO] Processing Complete for NVD CVE - 2017  (14071 ms)
[INFO] Processing Started for NVD CVE - 2019
[INFO] Processing Complete for NVD CVE - 2018  (12425 ms)
[INFO] Processing Started for NVD CVE - 2020
[INFO] Processing Complete for NVD CVE - 2019  (9792 ms)
[INFO] Processing Started for NVD CVE - 2021
[INFO] Processing Complete for NVD CVE - 2020  (10823 ms)
[INFO] Processing Started for NVD CVE - 2022
[INFO] Processing Complete for NVD CVE - 2021  (11030 ms)
[INFO] Processing Started for NVD CVE - 2023
[INFO] Processing Complete for NVD CVE - 2023  (193 ms)
[INFO] Processing Complete for NVD CVE - 2022  (10686 ms)
</code>
</pre>

My questions are:

1. What does the program do when it says its "Processing" a NVD CVE - <year> file?
2. Does the processing on the CVE file output a file to be used?
3. Can I tell the scan to use a previously processed version of the NVD CVE files?

Thank you in advance.

**Comment by HaGGi13** [comment]
Hi @Cosmin-Apopei,

**Regards 1.:**
This happens in the OWASP Dependency Check itself that is wrapped in this Azure DevOps extension.  
Here's the [code](https://github.com/jeremylong/DependencyCheck/blob/b560a72fd87db4559099fe3303d4b4f495b944b0/core/src/main/java/org/owasp/dependencycheck/data/update/nvd/ProcessTask.java#L150).

It seems to download the definition files and imports them. Indeed, there happens much more under the hood, therefore the aforementioned code reference.

**Regards 2.:**
Please see _Regards 1._

**Regards 3.:**
To reduce the execution time, you can cache all downloaded data. Please check this #110.
But, this works in Azure Pipelines only, it won't work for Azure DevOps Server <= 2019 (on-prem), because the Cache-task is not compatible/exists for this version. Regards Azure DevOps Server 2022 I cannot say.

**Comment by jeremylong** [comment]
I have no idea how the azure pipeline task is setup or used as the project is maintained by a different team.

In general - there is a data directory that should be cached. If you run the dependency-check update at least once evey 7 days only a very small XML file is downloaded and processed.

**Comment by Cosmin-Apopei** [comment]
Thank you both for your answers. Adding caching to my pipeline has reduced its time significantly.
